name: calendar_try1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_week_view: ^1.4.3
  url_launcher: ^6.1.10
  intl: ^0.18.0
  calendar_view: ^1.4.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  provider: ^6.1.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - lib/pages/login.png
